# Generated by Django 4.2.7 on 2023-12-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0002_alter_operation_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='canceled',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='done',
        ),
        migrations.AddField(
            model_name='offer',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
