# Generated by Django 5.0 on 2023-12-09 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0003_remove_operation_canceled_remove_operation_done_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='user',
        ),
        migrations.AddField(
            model_name='offer',
            name='userStock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='stockmarket.userstock'),
        ),
        migrations.AlterField(
            model_name='userstock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stocks', to='stockmarket.stock'),
        ),
        migrations.AlterField(
            model_name='userstock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stocks', to=settings.AUTH_USER_MODEL),
        ),
    ]
