# Generated by Django 5.0 on 2023-12-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0005_rename_userstock_offer_user_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='default_price',
            field=models.FloatField(default=100),
        ),
    ]
